#!/usr/bin/env bash

set -e

SHADOWSOCKS_PORT=${SHADOWSOCKS_PORT:-8388}
SHADOWSOCKS_SCERET=${SHADOWSOCKS_SECRET:-password}
SHADOWSOCKS_TIMEOUT=${SHADOWSOCKS_TIMEOUT:-10}
SHADOWSOCKS_MAXOPENFILES=${SHADOWSOCKS_MAXOPENFILES:-1024}

exec ss-server -s 0.0.0.0 -p ${SHADOWSOCKS_PORT} -m aes-256-cfb --fast-open -t ${SHADOWSOCKS_TIMEOUT} -k ${SHADOWSOCKS_SECRET} -n ${SHADOWSOCKS_MAXOPENFILES}
